export default actionTypes = {

    SIGNUP_PROG: "SIGNUP_PROG",
    SIGNUP_SUCC: "SIGNUP_SUCC",
    SIGNUP_FAIL: "SIGNUP_FAIL",

    SIGNIN_PROG: 'SIGNIN_PROG',
    SIGNIN_SUCC: 'SIGNIN_SUCC',
    SIGNIN_FAIL: 'SINGIN_FAIL',

    ADD_FERTILIZER_PROG: 'ADD_FERTILIZER_PROG',
    ADD_FERTILIZER_SUCC: 'ADD_FERTILIZER_SUCC',
    ADD_FERTILIZER_FAIL: 'ADD_FERTILIZER_FAIL',
    CLEAR_FERTILIZERS: 'CLEAR_FERTILIZERS',

    ADD_FERTILIZERS_RESPONSE_PROG: 'ADD_FERTILIZERS_RESPONSE_PROG',
    ADD_FERTILIZERS_RESPONSE_SUCC: 'ADD_FERTILIZERS_RESPONSE_SUCC',
    ADD_FERTILIZERS_RESPONSE_FAIL: 'ADD_FERTILIZERS_RESPONSE_FAIL',
    CLEAR_ADD_FERTILIZER_RESPONSE: 'CLEAR_ADD_FERTILIZER_RESPONSE',

    GET_CITY_LIST_PROG: 'GET_CITY_LIST_PROG',
    GET_CITY_LIST_SUCC: 'GET_CITY_LIST_SUCC',
    GET_CITY_LIST_FAIL: 'GET_CITY_LIST_FAIL',
    
    GET_CROPRATES_PROG: 'GET_CROPRATES_PROG',
    GET_CROPRATES_SUCC: 'GET_CROPRATES_SUCC',
    GET_CROPRATES_FAIL: 'GET_CROPRATES_FAIL',

    GET_WEATHER_PROG: 'GET_WEATHER_PROG',
    GET_WEATHER_SUCC: 'GET_WEATHER_SUCC',
    GET_WEATHER_FAIL: 'GET_WEATHER_FAIL',

    UPDATE_FERTILIZER_PROG: 'UPDATE_FERTILIZER_PROG',
    UPDATE_FERTILIZER_SUCC: 'UPDATE_FERTILIZER_SUCC',
    UPDATE_FERTILIZER_FAIL: 'UPDATE_FERTILIZER_FAIL',

    CLEAR_UPDATE_FERTILIZER: 'CLEAR_UPDATE_FERTILIZER',

    GET_FERTILIZER_PROG: 'GET_FERTILIZER_PROG',
    GET_FERTILIZER_SUCC: 'GET_FERTILIZER_SUCC',
    GET_FERTILIZER_FAIL: 'GET_FERTILIZER_FAIL',

    DELETE_FERTILIZER_PROG: 'DELETE_FERTILIZER_PROG',
    DELETE_FERTILIZER_SUCC: 'DELETE_FERTILIZER_SUCC',
    DELETE_FERTILIZER_FAIL: 'DELETE_FERTILIZER_FAIL',

    ADD_MACHINE_PROG: 'ADD_MACHINE_PROG',
    ADD_MACHINE_SUCC: 'ADD_MACHINE_SUCC',
    ADD_MACHINE_FAIL: 'ADD_MACHINE_FAIL',
    CLEAR_MACHINES: 'CLEAR_MACHINES',

    ADD_MACHINE_RESPONSE_PROG: 'ADD_MACHINE_RESPONSE_PROG',
    ADD_MACHINE_RESPONSE_SUCC: 'ADD_MACHINE_RESPONSE_SUCC',
    ADD_MACHINE_RESPONSE_FAIL: 'ADD_MACHINE_RESPONSE_FAIL',
    CLEAR_ADD_MACHINES_RESPONSE: 'CLEAR_ADD_MACHINES_RESPONSE',

    CLEAR_UPDATE_MACHINE: 'CLEAR_UPDATE_MACHINE',

    UPDATE_MACHINE_PROG: 'UPDATE_MACHINE_PROG',
    UPDATE_MACHINE_SUCC: 'UPDATE_MACHINE_SUCC',
    UPDATE_MACHINE_FAIL: 'UPDATE_MACHINE_FAIL',


    GET_MACHINE_PROG: 'GET_MACHINE_PROG',
    GET_MACHINE_SUCC: 'GET_MACHINE_SUCC',
    GET_MACHINE_FAIL: 'GET_MACHINE_FAIL',

    DELETE_MACHINE_PROG: 'DELETE_MACHINE_PROG',
    DELETE_MACHINE_SUCC: 'DELETE_MACHINE_SUCC',
    DELETE_MACHINE_FAIL: 'DELETE_MACHINE_FAIL',

    ADD_PESTICIDE_PROG: 'ADD_PESTICIDE_PROG',
    ADD_PESTICIDE_SUCC: 'ADD_PESTICIDE_SUCC',
    ADD_PESTICIDE_FAIL: 'ADD_PESTICIDE_FAIL',
    CLEAR_PESTICIDES: 'CLEAR_PESTICIDES',

    ADD_PESTICIDES_RESPONSE_PROG: 'ADD_PESTICIDES_RESPONSE_PROG',
    ADD_PESTICIDES_RESPONSE_SUCC: 'ADD_PESTICIDES_RESPONSE_SUCC',
    ADD_PESTICIDES_RESPONSE_FAIL: 'ADD_PESTICIDES_RESPONSE_FAIL',
    CLEAR_ADD_PESTICIDE_RESPONSE: 'CLEAR_ADD_PESTICIDE_RESPONSE',

    GET_PESTICIDE_PROG: 'GET_PESTICIDE_PROG',
    GET_PESTICIDE_SUCC: 'GET_PESTICIDE_SUCC',
    GET_PESTICIDE_FAIL: 'GET_PESTICIDE_FAIL',

    UPDATE_PESTICIDE_PROG: 'UPDATE_PESTICIDE_PROG',
    UPDATE_PESTICIDE_SUCC: 'UPDATE_PESTICIDE_SUCC',
    UPDATE_PESTICIDE_FAIL: 'UPDATE_PESTICIDE_FAIL',

    CLEAR_UPDATE_PESTICIDE: 'CLEAR_UPDATE_PESTICIDE',

    DELETE_PESTICIDE_PROG: 'DELETE_PESTICIDE_PROG',
    DELETE_PESTICIDE_SUCC: 'DELETE_PESTICIDE_SUCC',
    DELETE_PESTICIDE_FAIL: 'DELETE_PESTICIDE_FAIL',

    GET_FERTILIZER_MACHINES_PESTICIDES: 'GET_FERTILIZER_MACHINES_PESTICIDES',





    SET_USER: 'SET_USER',

    CLEAR_ERROR: "CLEAR_ERROR",

    GET_TOKEN_AND_USER: "GET_TOKEN_AND_USER",

    SIGN_OUT: "SIGN_OUT",

    SET_UNMOUNT_FLAG: "SET_UNMOUNT_FLAG",

    ADD_CROP_DATA_PROG: "ADD_CROP_DATA_PROG",
    ADD_CROP_DATA_SUCC: "ADD_CROP_DATA_SUCC",
    ADD_CROP_DATA_FAIL: "ADD_CROP_DATA_FAIL",
    CLEAR_ADD_CROP_RESPONSE: "CLEAR_ADD_CROP_RESPONSE",


    ADD_CROP_COMMENT_PROG: 'ADD_CROP_COMMENT_PROG',
    ADD_CROP_COMMENT_SUCC: 'ADD_CROP_COMMENT_SUCC',
    ADD_CROP_COMMENT_FAIL: 'ADD_CROP_COMMENT_FAIL',


    GET_CROP_PROG: 'GET_CROP_PROG',
    GET_CROP_SUCC: 'GET_CROP_SUCC',
    GET_CROP_FAIL: 'GET_CROP_FAIL',


    ADD_PROB_DATA_PROG: "ADD_PROB_DATA_PROG",
    ADD_PROB_DATA_SUCC: "ADD_PROB_DATA_SUCC",
    ADD_PROB_DATA_FAIL: "ADD_PROB_DATA_FAIL",
    CLEAR_ADD_PROB_RESPONSE: "CLEAR_ADD_PROB_RESPONSE",

    GET_CROPS_BY_ID_PROG: "GET_CROPS_BY_ID_PROG",
    GET_CROPS_BY_ID_SUCC: "GET_CROPS_BY_ID_SUCC",
    GET_CROPS_BY_ID_FAIL: "GET_CROPS_BY_ID_FAIL",

    GET_PROBLEMS_BY_ID_PROG: "GET_PROBLEMS_BY_ID_PROG",
    GET_PROBLEMS_BY_ID_SUCC: "GET_PROBLEMS_BY_ID_SUCC",
    GET_PROBLEMS_BY_ID_FAIL: "GET_PROBLEMS_BY_ID_FAIL",

    UPDATE_CROP_PROG: "UPDATE_CROP_PROG",
    UPDATE_CROP_SUCC: "UPDATE_CROP_SUCC",
    UPDATE_CROP_FAIL: "UPDATE_CROP_FAIL",
    CLEAR_UPDATE_CROP_RESPONSE: "CLEAR_UPDATE_CROP_RESPONSE",

    UPDATE_PROBLEM_PROG: "UPDATE_PROBLEM_PROG",
    UPDATE_PROBLEM_SUCC: "UPDATE_PROBLEM_SUCC",
    UPDATE_PROBLEM_FAIL: "UPDATE_PROBLEM_FAIL",
    CLEAR_UPDATE_PROB_RESPONSE: "CLEAR_UPDATE_PROB_RESPONSE",

    DELETE_PROBLEM_PROG: "DELETE_PROBLEM_PROG",
    DELETE_PROBLEM_SUCC: "DELETE_PROBLEM_SUCC",
    DELETE_PROBLEM_FAIL: "DELETE_PROBLEM_FAIL",

    DELETE_CROP_PROG: "DELETE_CROP_PROG",
    DELETE_CROP_SUCC: "DELETE_CROP_SUCC",
    DELETE_CROP_FAIL: "DELETE_CROP_FAIL",

    GET_MACHINERY_PROG: "GET_MACHINERY_PROG",
    GET_MACHINERY_SUCC: "GET_MACHINERY_SUCC",
    GET_MACHINERY_FAIL: "GET_MACHINERY_FAIL",

    GET_PESTICIDE_PROG: "GET_PESTICIDE_PROG",
    GET_PESTICIDE_SUCC: "GET_PESTICIDE_SUCC",
    GET_PESTICIDE_FAIL: "GET_PESTICIDE_FAIL",

    GET_FERTILIZER_PROG: "GET_FERTILIZER_PROG",
    GET_FERTILIZER_SUCC: "GET_FERTILIZER_SUCC",
    GET_FERTILIZER_FAIL: "GET_FERTILIZER_FAIL",

    SUBMIT_MACHINERY_RESPONSE_PROG: "SUBMIT_MACHINERY_RESPONSE_PROG",
    SUBMIT_MACHINERY_RESPONSE_SUCC: "SUBMIT_MACHINERY_RESPONSE_SUCC",
    SUBMIT_MACHINERY_RESPONSE_FAIL: "SUBMIT_MACHINERY_RESPONSE_FAIL",

    SUBMIT_FERTILIZER_RESPONSE_PROG: "SUBMIT_FERTILIZER_RESPONSE_PROG",
    SUBMIT_FERTILIZER_RESPONSE_SUCC: "SUBMIT_FERTILIZER_RESPONSE_SUCC",
    SUBMIT_FERTILIZER_RESPONSE_FAIL: "SUBMIT_FERTILIZER_RESPONSE_FAIL",

    SUBMIT_PESTICIDE_RESPONSE_PROG: "SUBMIT_PESTICIDE_RESPONSE_PROG",
    SUBMIT_PESTICIDE_RESPONSE_SUCC: "SUBMIT_PESTICIDE_RESPONSE_SUCC",
    SUBMIT_PESTICIDE_RESPONSE_FAIL: "SUBMIT_PESTICIDE_RESPONSE_FAIL",

    CLEAR_MACHINERY_SUBMIT_RESPONSE: "CLEAR_MACHINERY_SUBMIT_RESPONSE",
    CLEAR_PESTICIDE_SUBMIT_RESPONSE: "CLEAR_PESTICIDE_SUBMIT_RESPONSE",
    CLEAR_FERTILIZER_SUBMIT_RESPONSE: "CLEAR_FERTILIZER_SUBMIT_RESPONSE",

    GET_CROP_DETAILS_PROG: "GET_CROP_DETAILS_PROG",
    GET_CROP_DETAILS_SUCC: "GET_CROP_DETAILS_SUCC",
    GET_CROP_DETAILS_FAIL: "GET_CROP_DETAILS_FAIL",

    GET_ALL_PROBLEMS_PROG: "GET_ALL_PROBLEMS_PROG",
    GET_ALL_PROBLEMS_SUCC: "GET_ALL_PROBLEMS_SUCC",
    GET_ALL_PROBLEMS_FAIL: "GET_ALL_PROBLEMS_FAIL",

    ADD_FARMER_PROBLEM_COMMENT_PROG: "ADD_FARMER_PROBLEM_COMMENT_PROG",
    ADD_FARMER_PROBLEM_COMMENT_SUCC: "ADD_FARMER_PROBLEM_COMMENT_SUCC",
    ADD_FARMER_PROBLEM_COMMENT_FAIL: "ADD_FARMER_PROBLEM_COMMENT_FAIL",


    ADD_CROP_DETAILS_COMMENT_PROG: "ADD_CROP_DETAILS_COMMENT_PROG",
    ADD_CROP_DETAILS_COMMENT_SUCC: "ADD_CROP_DETAILS_COMMENT_SUCC",
    ADD_CROP_DETAILS_COMMENT_FAIL: "ADD_CROP_DETAILS_COMMENT_FAIL",

    GET_ALL_USERS_PROG: "GET_ALL_USERS_PROG",
    GET_ALL_USERS_SUCC: "GET_ALL_USERS_SUCC",
    GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",

    GET_PRIVATE_CONVERSATION_PROG: "GET_PRIVATE_CONVERSATION_PROG",
    GET_PRIVATE_CONVERSATION_SUCC: "GET_PRIVATE_CONVERSATION_SUCC",
    GET_PRIVATE_CONVERSATION_FAIL: "GET_PRIVATE_CONVERSATION_FAIL"


}